### ISSUE TITLE
Python Client

### ISSUE THREAD

**Issue by einarf** [rocket/rocket#53]
https://github.com/Contraz/pyrocket

Squeezed out in a day, but it does the job. Missing a few trivial things I'll fix in the next couple of days.

**Comment by kusma** [comment]
Cool stuff! I guess we should add a link in the readme?

**Comment by einarf** [comment]
That would be great. Doing some polish on the project as we speak. Should be more or less feature complete now.

I can make a PR if you feel extremely lazy today.

**Comment by einarf** [comment]
Ninja #54

**Comment by kusma** [comment]
@einarf: Awesome, thanks!
