### ISSUE TITLE
Support Mac ⌘-Ctrl swap

### ISSUE THREAD

**Issue by grant-h** [rocket/rocket#55]
While trying to use the editor on Mac, many of the commands overlap with Exposé which makes them not usable.

Support for Mac OSX specific keybinds or a way to remap keys would be ideal.

**Comment by kusma** [comment]
@grant-h: why did you close this? Did you find a work-around?

**Comment by grant-h** [comment]
@kusma I closed it because It looks like Cmd is correctly mapped on MacOSX. I made a mistake in that I was trying to use bias up (Cmd+PgUp) on a row with an unset value. My intuition said that no matter what it should bring the value to 1.0. Overall I think Rocket could use some UX love!

**Comment by kusma** [comment]
@grant-h: Thanks for clarifying. Yeah, I'm sure there's a lot that can be made better in terms of UX. I'm not entirely sure what case you're describing here (unset, as in, empty, or half-way entered value?), but if there's some particularly annoying cases, feel free to describe them properly, and I can look into improving the UX...

**Comment by grant-h** [comment]
@kusma Thanks! I meant unset as in empty (---). I ran in to an issue where I was trying to sync rocket to an MP3 in a JavaScript. My idea of getting it synced up was to hit play, have my target track selected, and then hitting the Bias Up command while rocket was running. This also hit another issue in that it doesn't appear from my limited testing that you can change row values during playback. I'd be interesting in contributing where I can or providing more details. I'm not a heavy Rocket user, but I think it's a great tool!
