### ISSUE TITLE
Random order of XML attributes when saving

### ISSUE THREAD

**Issue by mgunyho** [rocket/rocket#73]
If I open a syncdata file and save it, the attributes in the XML `row`, `value` and `interpolation` are shuffled each time, and git thinks all keys in the file have been rewritten. This makes merging files a headache. Apparently, this is caused by `QDomElement.setAttribute` ([here](https://github.com/rocket/rocket/blob/901db86412a0d57600cb072c16deac9c3ebc709d/editor/syncdocument.cpp#L128)) storing the keys in a hashmap, which shuffles the keys on purpose (see [here](https://stackoverflow.com/questions/21535707/incorrect-order-of-attributes-in-qt-xml)). This could be fixed by seeding the hash as suggested in the SO thread.

**Comment by kusma** [comment]
Hmm, interesting. I haven't seen this behavior myself, so I wonder if this is dependent on Qt versions... I also wasn't aware that QtXML is deprecated, which I think is a strong argument to rewrite the code to use  `QXmlStreamReader`/`QXmlStreamWriter` instead... I think the old Qt4 support can be binned anyway.

**Comment by kusma** [comment]
This behavior started in Qt5.6. The automated windows build (which is what I use) use Qt5.5. This explains why I haven't seen this behavior.

Thanks for reporting. I think a quick fix should be easy to do, like you suggest.

**Comment by kusma** [comment]
Hmm, I just tried to reproduce this on Qt 5.11 on Ubuntu, and I seem to get consistent behavior...

@mgunyho: What environment do you trigger this under?

**Comment by kusma** [comment]
OK, never mind. I managed to trigger it after some more tries. I had to restart the editor in between, I guess the hash stays constant.

**Comment by kusma** [comment]
@mgunyho: OK, could you check if #74 fixes the issue for you?

**Comment by mgunyho** [comment]
Seems to work, thanks!
