### ISSUE TITLE
New (co-)maintainer wanted

### ISSUE THREAD

**Issue by kusma** [rocket/rocket#80]
I sadly no longer have the time and motivation to actively maintain Rocket, and it's unlikely that I'll find that time and motivation anytime soon. I suspect this has been evident from the lack of activity for a while. But I would love to see this work continue, so it would be great if someone else were interested in picking things up.

I'm not planning on entirely stepping away anytime soon, I'll be around to help review merge-requests etc. But I'd love to have a bit more of a contingency-plan here. But I *do* plan on stepping **down** from the maintainer role in the long term, given that someone steps up to the task. I don't want to get in anyone's way ;)

It's a small project, so the task isn't very big. It's mostly about providing code-reviews and merging once things are ready, producing releases and tending to automation. 

Any takers? If so, please let me know by posting a reply here.

**Comment by PoroCYon** [comment]
I guess I could help a bit? I'm not completely unfamiliar with the codebase, but I'm not sure if I'm completely the right person to be a maintainer. But maybe if nobody else volunteers?

**Comment by paulgoetze** [comment]
@kusma Maybe posting this repo on [adoptoposs.org](https://adoptoposs.org) might also help find new (co-)maintainers?

**Comment by luis2048** [comment]
I volunteer to maintain JS / TS version.

**Comment by kusma** [comment]
@PoroCYon, @luis2048: Awesome, thanks. I've invited both of you to the organization, and will set you up with maintainer permissions once I figure out the details. 

@paulgoetze: Thanks for the suggestion. Right now, I would prefer to limit my search within the demoscene, because of trust reasons. But perhaps I will come back to the suggestion down the line. Nice service, by the way 👍

**Comment by kusma** [comment]
@PoroCYon, @luis2048: OK, I've finally gotten around to making you organization owners. Thanks for stepping up, although there's been very low activity lately anyway :)

**Comment by kusma** [comment]
I'll close this issue for now, as I consider this at least partially resolved ;)
